config/routes.rb
Rails.application.routes.draw do
  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:service_number, :severity_critical, :severity_major, :severity_minor, :service_title, :reported_by, :date_reported, :dept_unit_section, :contact_number, :affected_modules, :request_type_software_defect, :request_type_configuration, :request_type_data_fix, :request_type_desktop_problem, :request_type_preventive_maintenance, :request_type_program_enhancement, :request_type_report_request, :request_type_new_system, :request_type_new_system, :request_type_others, :request_details, :attachments, :request_reported_by, :request_reported_by_date, :request_endorsed_by, :request_endorsed_by_date, :request_approved_by, :request_approved_by_date, :findings, :assessment_software_defect, :assessment_configuration, :assessment_enhancement, :assessment_data, :assessment_business_process, :assessment_others, :assessed_by, :assessment_date, :recommendations, :recommendation_endorsed_by, :recommendation_date, :results_attachments_test_scenarios, :results_attachments_test_results, :results_attachments_sample_output, :tested_by, :tested_by_date, :conclusion_accepted, :conclusion_rejected, :conclusion_reason, :conclusion_by, :conclusion_by_date, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OHIX</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<section id="service-request-listing">
<center><h1>Service Requests</h1>
<h4><%=DateTime.now.to_date%></h4>
</center>
<div class="container-fluid row">
<div class="col-md-1"></div>
<div class="col-md-10">
  <div class="panel panel-default x-scroll">
    <!-- Default panel contents -->
    <!-- Table -->
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Service number</th>
        <th>Service title</th>
        <th>Severity</th>
        <th>Reported by</th>
        <th>Date reported</th>
        <th>Dept unit section</th>
        <th>Contact number</th>
        <th>Affected modules</th>
        <th>Request Type</th>
        <th>Request details</th>
        <th>Attachments</th>
        <th>Request endorsed by</th>
        <th>Request endorsed by date</th>
        <th>Request approved by</th>
        <th>Request approved by date</th>
        <th>Findings</th>
        <th>Assessment </th>
        <th>Assessed by</th>
        <th>Assessment date</th>
        <th>Deadline</th>
        <th>Recommendations</th>
        <th>Recommendation endorsed by</th>
        <th>Recommendation date</th>
        <th>Results attachments test scenarios</th>
        <th>Results attachments test results</th>
        <th>Results attachments sample output</th>
        <th>Tested by</th>
        <th>Tested by date</th>
        <th>Conclusion</th>
        <th>Conclusion reason</th>
        <th>Conclusion by</th>
        <th>Conclusion by date</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @requests.each do |request| %>
      <%severity=""%>
      <%if request.severity_critical==true%>
        <%severity="critical"%>
      <%elsif request.severity_major==true%>
        <%severity="major"%>
      <%elsif request.severity_minor==true%>
        <%severity="minor"%>
      <%end%>

      <%r_type=""%>
      <%if request.request_type_configuration==true%>
        <%r_type="Configuration"%>
      <%elsif request.request_type_software_defect==true%>
        <%r_type="Software Defect"%>
      <%elsif request.request_type_data_fix==true%>
        <%r_type="Data Fix"%>
      <%elsif request.request_type_desktop_problem==true%>
      <%r_type="Desktop Problem"%>
      <%elsif request.request_type_preventive_maintenance==true%>
      <%r_type="Preventive Maintenance"%>
      <%elsif request.request_type_program_enhancement==true%>
      <%r_type="Program Enhancement"%>
      <%elsif request.request_type_report_request==true%>
      <%r_type="Report Request"%>
      <%elsif request.request_type_new_system==true%>
      <%r_type="New System"%>
      <%else%>
      <%r_type=request.request_type_others%>
      <%end%>

      <%assessment=""%>
      <%if request.assessment_software_defect==true%>
        <%assessment="Software Defect"%>
      <%elsif request.assessment_configuration==true%>
        <%assessment="Configuration"%>
      <%elsif request.assessment_enhancement==true%>
        <%assessment="Enhancement"%>
      <%elsif request.assessment_data==true%>
      <%assessment="Data"%>
      <%elsif request.assessment_business_process==true%>
      <%assessment="Business Process"%>
      <%else%>
      <%assessment=request.assessment_others%>
      <%end%>

      <%conclusion=""%>
      <%if request.conclusion_accepted==true%>
        <%conclusion="Accepted"%>
      <%elsif request.conclusion_rejected==true%>
        <%conclusion="rejected"%>
      <%end%>
        <tr>
          <td><%= request.service_number %></td>
          <td><%= request.service_title %></td>
          <td><%= severity %></td>
          <td><%= request.reported_by %></td>
          <td><%= request.date_reported %></td>
          <td><%= request.dept_unit_section %></td>
          <td><%= request.contact_number %></td>
          <td><%= request.affected_modules %></td>
          <td><%= r_type %></td>
          <td><%= request.request_details %></td>
          <td><%= request.attachments %></td>
          <td><%= request.request_endorsed_by %></td>
          <td><%= request.request_endorsed_by_date %></td>
          <td><%= request.request_approved_by %></td>
          <td><%= request.request_approved_by_date %></td>
          <td><%= request.findings %></td>
          <td><%= assessment%></td>
          <td><%= request.assessed_by %></td>
          <td><%= request.assessment_date %></td>
          <td><%= request.deadline%></td>
          <td><%= request.recommendations %></td>
          <td><%= request.recommendation_endorsed_by %></td>
          <td><%= request.recommendation_date %></td>
          <td><%= request.results_attachments_test_scenarios %></td>
          <td><%= request.results_attachments_test_results %></td>
          <td><%= request.results_attachments_sample_output %></td>
          <td><%= request.tested_by %></td>
          <td><%= request.tested_by_date %></td>
          <td><%= conclusion%></td>
          <td><%= request.conclusion_reason %></td>
          <td><%= request.conclusion_by %></td>
          <td><%= request.conclusion_by_date %></td>
          <td><%= link_to 'Show', request %></td>
          <td><%= link_to 'Edit', edit_request_path(request) %></td>
          <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
</div>
<center><%= link_to 'New Request', new_request_path, :class=>"btn btn1 add-sr"%></center>
</section>

app/views/requests/new.html.erb
<section id="new-service-request" class="container-fluid row">
<div class="col-md-2"></div>
<div class="col-md-8 card">
<div style="padding-top:10px;"><center><span style="font-size:40px;">Service Request</span> <%= link_to 'Back', requests_path, :style=>"float:right;",:class=>"btn btn-default" %></center></div><hr>
<%= form_for(@request) do |f| %>
<div class="view">

  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_number, "SR Number:" %> <%= f.number_field :service_number %>
  </div>
  <hr>
  <b>Severity Level:</b>
  <div class="field container-fluid row">
    <div class="col-md-2">
      <%= f.check_box :severity_critical,:class=>"chb" %> <%= f.label :severity_critical,"Critical" %>
    </div>
    <div class="col-md-2">
      <%= f.check_box :severity_major,:class=>"chb" %> <%= f.label :severity_major,"Major" %>
    </div>
    <div class="col-md-2">
      <%= f.check_box :severity_minor,:class=>"chb" %> <%= f.label :severity_minor,"Minor" %>
    </div>
    <script type="text/javascript">
      $(".chb").each(function()
      {
          $(this).change(function()
          {
              $(".chb").prop('checked',false);
              $(this).prop('checked',true);
          });
      });
    </script>
  </div>
  <hr>
  <div class="field container-fluid row">
	  <div class="row">
	    <div class="col-md-3">
	      <%= f.label :service_title, "SR Title:" %> <%= f.text_field :service_title %>
	    </div>
	    <div class="col-md-3">
	      <%= f.label :reported_by,"Reported by:" %><%= f.text_field :reported_by %>
	    </div>
	    <div class="col-md-6">
	      <%= f.label :date_reported, "Date Reported:" %><%= f.date_select :date_reported %>
	    </div>
	</div>
	<br>
	<div class="row">
	  <div class="col-md-4">
	    <%= f.label :dept_unit_section %> <%= f.text_field :dept_unit_section %>
	  </div>
	  <div class="col-md-4">
	    <%= f.label :contact_number %> <%= f.text_field :contact_number %>
	  </div>
	  <div class="col-md-4">
	    <%= f.label :affected_modules %> <%= f.text_field :affected_modules %>
  	  </div>
	</div>
  </div>
  <hr>
  <b>Request Type:</b>
  <div class="container-fluid row field">
    <div class="col-md-3">
      <%= f.check_box :request_type_software_defect,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_software_defect,"Software Defect" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_configuration,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_configuration,"Configuration" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_data_fix,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_data_fix,"Data Fix" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_desktop_problem,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_desktop_problem,"Desktop Problem" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_preventive_maintenance,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_preventive_maintenance,"Preventive Maintenance" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_program_enhancement,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_program_enhancement,"Program Enhancement" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_report_request,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_report_request,"Report Request" %>
    </div>
    <div class="col-md-3">
      <%= f.check_box :request_type_new_system,:class=>"chb1",:onClick=>"Hide('others_box', this);" %> <%= f.label :request_type_new_system,"New System" %>
    </div>
    <div class="col-md-3">
      <input id="other-b" type="checkbox" class="chb1" onClick="Reveal('others_box', this);"> <label for="other-b">Other</label><br>
      <%= f.text_field :request_type_others,:id=>"others_box" %>
    </div>
  </div>
  <script type="text/javascript">
      $(".chb1").each(function()
    {
        $(this).change(function()
        {
            $(".chb1").prop('checked',false);
            $(this).prop('checked',true);
        });
    });
  </script>
  <hr>
  <b>REQUEST DETAILS:<b>
  <div class="container-fluid field">
  	<div class="row">
	  <div class="col-md-9">
	    <%= f.label :request_details, "Describe the nature of the request or details of the problem encountered." %>
	  </div>
	  <div class="col-md-3">
	    <%= f.check_box :attachments %> <%= f.label :attachments %>
	  </div>
	</div>  
	<div class="row">
	   <%= f.text_area :request_details, cols: "100", rows: "5" %>
	</div>  
	<br>
	<!--<div class="row">
	   <div class="col-md-6">
	    <%= f.label :request_reported_by, "Reported by:" %> <%= f.text_field :request_reported_by %>
	  </div>
	  <div class="col-md-6">
	    <%= f.label :request_reported_by_date %> <%= f.date_select :request_reported_by_date %>
	  </div>
	</div>  
	<br>-->
    <div class="row">
	  <div class="col-md-5">
		<%= f.label :request_endorsed_by, "Endorsed by:" %> <%= f.text_field :request_endorsed_by %>
	  </div>
	  <div class="col-md-6">
	    <%= f.label :request_endorsed_by_date, "Date Endorsed:" %> <%= f.date_select :request_endorsed_by_date %>
	  </div>
	</div>  
	<br>
    <div class="row">
	  <div class="col-md-5">
	    <%= f.label :request_approved_by, "Approved By:" %> <%= f.text_field :request_approved_by %>
	  </div>
	  <div class="col-md-6">
	    <%= f.label :request_approved_by_date, "Date Approved:" %> <%= f.date_select :request_approved_by_date %>
	  </div>
	</div>  
  </div>
  <hr>
  <b>FINDINGS:</b>
  <div class="field">
    <%= f.text_area :findings, cols: "100", rows: "5"  %>
  </div>
  <hr>
  <b>Problem Assessment:</b>
    <div class="container-fluid row">
	  <div class="col-md-3">
	    <%= f.check_box :assessment_software_defect,:class=>"chb4",:onClick=>"Hide('others_box1', this);" %> <%= f.label :assessment_software_defect, "Software Defect" %><br>
	    <%= f.check_box :assessment_configuration,:class=>"chb4",:onClick=>"Hide('others_box1', this);" %> <%= f.label :assessment_configuration, "Configuration" %>
	  </div>
	  <div class="col-md-3">
	    <%= f.check_box :assessment_enhancement,:class=>"chb4",:onClick=>"Hide('others_box1', this);" %> <%= f.label :assessment_enhancement,"Enhancement" %><br>
	    <%= f.check_box :assessment_data,:class=>"chb4",:onClick=>"Hide('others_box1', this);" %> <%= f.label :assessment_data, "Data" %>
	  </div>
	  <div class="col-md-3">
	    <%= f.check_box :assessment_business_process,:class=>"chb4",:onClick=>"Hide('others_box1', this);" %> <%= f.label :assessment_business_process, "Business Process" %><br>
	      <input id="other-b1" type="checkbox" class="chb4" onClick="Reveal('others_box1', this);"> <label for="other-b1">Other</label><br>
	      <%= f.text_field :assessment_others,:id=>"others_box1" %>
	  </div>
	</div>
	  <script type="text/javascript">
      $(".chb4").each(function()
    {
        $(this).change(function()
        {
            $(".chb4").prop('checked',false);
            $(this).prop('checked',true);
        });
    });
      </script>
	<hr>
	<div class="container-fluid row">
	  <div class="col-md-5">
	   <%= f.label :assessed_by, "Assessed By:" %> <%= f.text_field :assessed_by %>
	  </div>
	  <div class="col-md-6">
	    <%= f.label :assessment_date, "Date Assessed:" %> <%= f.date_select :assessment_date %>
	  </div>
	</div>
	<br>
  <div class="field">
    <%= f.label :recommendations %><br>
    <%= f.text_area :recommendations, cols: "100", rows: "5" %>
  </div>
  <br>
  <div class="container-fluid row">
	<div class="col-md-5">
	   <%= f.label :recommendation_endorsed_by, "Recommended By:" %><%= f.text_field :recommendation_endorsed_by %>
	</div>
	<div class="col-md-6">
	    <%= f.label :recommendation_date, "Date of Recommended:" %><%= f.date_select :recommendation_date %>
	</div>
  </div>
  <hr>
  <b>ACCEPTANCE OF RESULTS</b> (for service rendered) <br>
  <b>Attachments</b>
    <div class="container-fluid row field">
 		  <div class="col-md-3">
		    <%= f.check_box :results_attachments_test_scenarios,:class=>"chb2" %> <%= f.label :results_attachments_test_scenarios, "Test Scenarios" %>
		  </div>
		  <div class="col-md-3">
		    <%= f.check_box :results_attachments_test_results,:class=>"chb2" %> <%= f.label :results_attachments_test_results, "Test Results" %>
		  </div>
		  <div class="col-md-3">
		    <%= f.check_box :results_attachments_sample_output,:class=>"chb2" %> <%= f.label :results_attachments_sample_output, "Sample Output" %>
  		  </div>
  	</div>
  <script type="text/javascript">
      $(".chb2").each(function()
    {
        $(this).change(function()
        {
            $(".chb2").prop('checked',false);
            $(this).prop('checked',true);
        });
    });
  </script>
  <hr>
    <div class="container-fluid row field">
	  <div class="col-md-5">
	    <%= f.label :tested_by,"Tested By:" %> <%= f.text_field :tested_by %>
	  </div>
	  <div class="col-md-6">
	    <%= f.label :tested_by_date, "Date Tested:" %> <%= f.date_select :tested_by_date %>
	  </div>
  	</div>
  	<hr>
  	<b>CONCLUSION</b>
  	<div class="container-fluid row field">
	    <div class="col-md-4">
		    <%= f.check_box :conclusion_accepted,:class=>"chb3" %> <%= f.label :conclusion_accepted, "Accepted" %>
		</div>
		<div class="col-md-4">
		    <%= f.check_box :conclusion_rejected,:class=>"chb3" %> <%= f.label :conclusion_rejected, "Rejected" %>
		</div>
  	</div>
  <script type="text/javascript">
      $(".chb3").each(function()
    {
        $(this).change(function()
        {
            $(".chb3").prop('checked',false);
            $(this).prop('checked',true);
        });
    });
  </script>
  <div class="field">
    <%= f.label :conclusion_reason %><br>
    <%= f.text_area :conclusion_reason, cols: "100", rows: "2" %>
  </div>
  <br>
  <div class="container-fluid row field">
	  <div class="col-md-5">
	    <%= f.label :conclusion_by, "By:" %><%= f.text_field :conclusion_by %>
	  </div>
	  <div class="col-md-6">
	    <%= f.label :conclusion_by_date, "Date Concluded:" %><%= f.date_select :conclusion_by_date %>
	  </div>
  </div>
 	<br>
  <div class="field">
    <%= f.label :deadline %><%= f.date_select :deadline %>
  </div>
  <hr>

<script type="text/javascript"> 
function Reveal (it, box) { 
var vis = (box.checked) ? "block" : "none"; 
document.getElementById(it).style.display = vis;
} 

function Hide (it, box) { 
var vis = (box.checked) ? "none" : "none"; 
document.getElementById(it).style.display = vis;
} 
</script>
</div>
<center>
 <div class="actions submit-new-service-request">
    <%= f.submit "Submit",:class=>"btn btn-default",:style=>"width:100px;" %>
  </div>
<% end %>
</center>
</div>
</section>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service number:</strong>
  <%= @request.service_number %>
</p>

<p>
  <strong>Severity critical:</strong>
  <%= @request.severity_critical %>
</p>

<p>
  <strong>Severity major:</strong>
  <%= @request.severity_major %>
</p>

<p>
  <strong>Severity minor:</strong>
  <%= @request.severity_minor %>
</p>

<p>
  <strong>Service title:</strong>
  <%= @request.service_title %>
</p>

<p>
  <strong>Reported by:</strong>
  <%= @request.reported_by %>
</p>

<p>
  <strong>Date reported:</strong>
  <%= @request.date_reported %>
</p>

<p>
  <strong>Dept unit section:</strong>
  <%= @request.dept_unit_section %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @request.contact_number %>
</p>

<p>
  <strong>Affected modules:</strong>
  <%= @request.affected_modules %>
</p>

<p>
  <strong>Request type software defect:</strong>
  <%= @request.request_type_software_defect %>
</p>

<p>
  <strong>Request type configuration:</strong>
  <%= @request.request_type_configuration %>
</p>

<p>
  <strong>Request type data fix:</strong>
  <%= @request.request_type_data_fix %>
</p>

<p>
  <strong>Request type desktop problem:</strong>
  <%= @request.request_type_desktop_problem %>
</p>

<p>
  <strong>Request type preventive maintenance:</strong>
  <%= @request.request_type_preventive_maintenance %>
</p>

<p>
  <strong>Request type program enhancement:</strong>
  <%= @request.request_type_program_enhancement %>
</p>

<p>
  <strong>Request type report request:</strong>
  <%= @request.request_type_report_request %>
</p>

<p>
  <strong>Request type new system:</strong>
  <%= @request.request_type_new_system %>
</p>

<p>
  <strong>Request type new system:</strong>
  <%= @request.request_type_new_system %>
</p>

<p>
  <strong>Request type others:</strong>
  <%= @request.request_type_others %>
</p>

<p>
  <strong>Request details:</strong>
  <%= @request.request_details %>
</p>

<p>
  <strong>Attachments:</strong>
  <%= @request.attachments %>
</p>

<p>
  <strong>Request reported by:</strong>
  <%= @request.request_reported_by %>
</p>

<p>
  <strong>Request reported by date:</strong>
  <%= @request.request_reported_by_date %>
</p>

<p>
  <strong>Request endorsed by:</strong>
  <%= @request.request_endorsed_by %>
</p>

<p>
  <strong>Request endorsed by date:</strong>
  <%= @request.request_endorsed_by_date %>
</p>

<p>
  <strong>Request approved by:</strong>
  <%= @request.request_approved_by %>
</p>

<p>
  <strong>Request approved by date:</strong>
  <%= @request.request_approved_by_date %>
</p>

<p>
  <strong>Findings:</strong>
  <%= @request.findings %>
</p>

<p>
  <strong>Assessment software defect:</strong>
  <%= @request.assessment_software_defect %>
</p>

<p>
  <strong>Assessment configuration:</strong>
  <%= @request.assessment_configuration %>
</p>

<p>
  <strong>Assessment enhancement:</strong>
  <%= @request.assessment_enhancement %>
</p>

<p>
  <strong>Assessment data:</strong>
  <%= @request.assessment_data %>
</p>

<p>
  <strong>Assessment business process:</strong>
  <%= @request.assessment_business_process %>
</p>

<p>
  <strong>Assessment others:</strong>
  <%= @request.assessment_others %>
</p>

<p>
  <strong>Assessed by:</strong>
  <%= @request.assessed_by %>
</p>

<p>
  <strong>Assessment date:</strong>
  <%= @request.assessment_date %>
</p>

<p>
  <strong>Recommendations:</strong>
  <%= @request.recommendations %>
</p>

<p>
  <strong>Recommendation endorsed by:</strong>
  <%= @request.recommendation_endorsed_by %>
</p>

<p>
  <strong>Recommendation date:</strong>
  <%= @request.recommendation_date %>
</p>

<p>
  <strong>Results attachments test scenarios:</strong>
  <%= @request.results_attachments_test_scenarios %>
</p>

<p>
  <strong>Results attachments test results:</strong>
  <%= @request.results_attachments_test_results %>
</p>

<p>
  <strong>Results attachments sample output:</strong>
  <%= @request.results_attachments_sample_output %>
</p>

<p>
  <strong>Tested by:</strong>
  <%= @request.tested_by %>
</p>

<p>
  <strong>Tested by date:</strong>
  <%= @request.tested_by_date %>
</p>

<p>
  <strong>Conclusion accepted:</strong>
  <%= @request.conclusion_accepted %>
</p>

<p>
  <strong>Conclusion rejected:</strong>
  <%= @request.conclusion_rejected %>
</p>

<p>
  <strong>Conclusion reason:</strong>
  <%= @request.conclusion_reason %>
</p>

<p>
  <strong>Conclusion by:</strong>
  <%= @request.conclusion_by %>
</p>

<p>
  <strong>Conclusion by date:</strong>
  <%= @request.conclusion_by_date %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @request.deadline %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>